- name: Gathering Facts
  hosts: clients 
  remote_user: root 
  gather_facts: yes 

  tasks:
  - name: create a var to store gathered facts 
    debug:
      var: ansible_facts
  
  - name: print all gathered facts from the variable 
    debug:
      msg: "{{ ansible_facts }}"