- name: Create user3 with encrypted password
  hosts: clients
  remote_user: root 
  vars:
    secret: Secure123
  
  tasks:
  - name: Creating user3 with encrypted password
    user: 
      name: euser3 
      password: "{{ secret | password_hash('sha512') }}"
      state: present